// <auto-generated />
namespace DistriBotAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class m22017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m22017));
        
        string IMigrationMetadata.Id
        {
            get { return "201702010140395_m2-2017"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
